#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on 04.01.2015 ... */ 
#define XMLRPC_C_VERSION "1.25.30" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 25 
#define XMLRPC_VERSION_POINT 30 
#endif 
